config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :records
  get 'coding' => "records#coding"

=======
>>>>>>> 28662242ddbd17f449c5fc5a5e0f94bad165dc61

  root :to => "pages#index"
  get '/pages/claim', to: 'pages#claim'
  get '/pages/annotation', to: 'pages#annotation'
  get '/pages/decision', to: 'pages#decision'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
  end

  def claim
    # @doc = Docx::Document.open("../patest.docx")
  end


  def annotation
  end

  def decision
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all.order_by_rand(seed: 28)
  end

  def coding
    @records = Record.all.order_by_rand(seed: 28)
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:pid, :docid, :history, :impression, :codes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fastehr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#">Fast-EHR</a>
         <ul class="nav">
          <li><%= link_to 'Home', root_path,:class => 'glyphicons icon-home' %></li>
        </ul>
      </div> <!-- Container closing div -->
    </div> <!-- navbar-inner closing div -->
  </div>  <!-- navbar-fixed-top -->
  <div class="container">
    <div class="content">
      <div class="wrapper">
        <div class="proper-content">
          <div class="row">
            <div class="span12">
              <%= yield %>
            </div> <!-- span12 -->
          </div> <!-- row -->
        </div> <!-- proper-content -->

        <div class="push"></div>
      </div><!-- /.wrapper -->
      <div class="footer-wrapper">
        <footer>
          <hr>
          <div class="row">
            <div class="span2">
              <%= button_to "   claim    ", pages_claim_path, :method => :get, :class => "btn btn-primary btn-large"  %>
            </div>
            <div class="span2">
              <%= button_to "annotation", pages_annotation_path, :method => :get, :class => "btn btn-primary btn-large"  %>
            </div>
            <div class="span2">
              <%= button_to "decision", pages_decision_path, :method => :get, :class => "btn btn-primary btn-large"  %>
            </div>
          </div>
          <hr>
          </footer>
      </div>
    </div> <!-- content -->
  </div>

</body>
</html>

app/views/pages/index.html.erb
<body class="welcome-page">
<div class="text_wel"
  <h1><b>Welcome!!</b></h1></br>
  <h4><u>Fast-EHR</u> is a tool used for automatic processing</br>of EHR documents to generate <i><u>ICD9 codes</u></i> for timely</br>
healthcare delivery, reporting and billing</br> and reimbursement  </h4>
</br>
</div>
</body>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br>
    <%= f.number_field :pid %>
  </div>
  <div class="field">
    <%= f.label :docid %><br>
    <%= f.number_field :docid %>
  </div>
  <div class="field">
    <%= f.label :history %><br>
    <%= f.text_area :history %>
  </div>
  <div class="field">
    <%= f.label :impression %><br>
    <%= f.text_area :impression %>
  </div>
  <div class="field">
    <%= f.label :codes %><br>
    <%= f.text_field :codes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/coding.html.erb
<br>
<h1><%= link_to 'Patient Visit Records', records_path %></h1>
<br>

<div id="sample_goal"></div>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Document id</th>
      <th>Medical History</th>
      <th>Radiology Impression</th>
      <th>ICD Codes</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each_with_index do |record,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= record.docid %></td>
        <td style="width:35%;"><%= record.history %></td>
        <td style="width:35%;"><%= record.impression %></td>
        <td style="width:200px; background:#CEF;"><%= record.codes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/javascript" charset="utf-8">

$(document).ready(function(){
 $('#sample_goal').goalProgress({
  goalAmount: 970,
  currentAmount: 970,
  speed: 10000,
  textBefore: '',
  textAfter: ' processed'
 });
});
</script>

<%= link_to 'New Record', new_record_path %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<br>
<h1>Patient Visit Records</h1>
<br>

<div class="trbutton"><%= link_to 'Generate ICD Codes', '/coding' %></div>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Document id</th>
      <th>Medical History</th>
      <th>Radiology Impression</th>
      <th>ICD Codes</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each_with_index do |record,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= record.docid %></td>
        <td style="width:35%;"><%= record.history %></td>
        <td style="width:35%;"><%= record.impression %></td>
        <td style="width:200px;"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @record.pid %>
</p>

<p>
  <strong>Docid:</strong>
  <%= @record.docid %>
</p>

<p>
  <strong>History:</strong>
  <%= @record.history %>
</p>

<p>
  <strong>Impression:</strong>
  <%= @record.impression %>
</p>

<p>
  <strong>Codes:</strong>
  <%= @record.codes %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>